### PR TITLE
feat(web,dal,sdf) - add new configuration frame with direction

### PR DESCRIPTION
**Pull request by vbustamante**
image

CLOSES ENG-2224
CLOSES ENG-2225
CLOSES ENG-2226
CLOSES ENG-2227
CLOSES ENG-2228
CLOSES ENG-2229
CLOSES ENG-2230

### CODE REVIEW

**Comment by vbustamante** [comment]
bors merge

**Comment by stack72** [comment]
bors cancel

**Comment by stack72** [comment]
bors merge

**Comment by vbustamante** [comment]
bors merge

**Comment by vbustamante** [comment]
bors merge

**Pull request merged**
