### PR TITLE
chore(dal,web,langjs,sdf,pkg): remove confirmations

### PR DESCRIPTION
**Pull request by paulocsanz**

### CODE REVIEW

**Comment by zacharyhamm** [comment]
my pr https://github.com/systeminit/si/pull/2719 will cause a merge conflict for this one. Easiest will probably be to merge this and then I'll fix the conflicts on my end. How close is this do you think? @paulocsanz

**Comment by paulocsanz** [comment]
It's ready, I can merge this right now. Happy to help fixing the conflict!

**Comment by paulocsanz** [comment]
bors merge

**Comment by zacharyhamm** [comment]
bors retry

**Comment by zacharyhamm** [comment]
net: http/tls handshake failed while pushing to docker (?!)

**Comment by zacharyhamm** [comment]
bors merge

**Comment by paulocsanz** [comment]
bors merge

**Comment by paulocsanz** [comment]
bors merge

**Pull request merged**
