### PR TITLE
Typo

### PR DESCRIPTION
**Pull request by LukeMathWalker**
Very nice intro, just spotted a typo while reading through!

### CODE REVIEW

**Comment by nickgerace** [comment]
Thank you @LukeMathWalker for that sentiment and the PR as well!

**Comment by nickgerace** [comment]
Once you add yourself to the contributors list, we will be good to go!

**Review by nickgerace — APPROVED** [review]

**Comment by LukeMathWalker** [comment]
Done!

**Comment by stack72** [comment]
bors merge

**Pull request merged**
