### PR TITLE
feat(dal): Don't create resources on copied components

### PR DESCRIPTION
**Pull request by vbustamante**

### CODE REVIEW

**Review by fnichol — APPROVED** [review]
That's so deliciously small and the variable change makes this *so* much clearer!

**Comment by vbustamante** [comment]
bors merge

**Comment by keeb** [comment]
bors try

**Comment by keeb** [comment]
bors merge

**Comment by fnichol** [comment]
bors retry

**Comment by vbustamante** [comment]
bors merge

**Comment by sprutton1** [comment]
bors merge

**Pull request merged**
