### PR TITLE
feat: use xxh3 hash instead of blake3 for merkle tree hash and content hashes

### PR DESCRIPTION
**Pull request by zacharyhamm**
Use a 128 bit hash instead of a 256 bit one. Removes a few megabytes from the initial graph.

NOTE: this is a breaking change, you'll need to clear your databases and start over.

### CODE REVIEW

**Comment by zacharyhamm** [comment]
bors try

**Comment by zacharyhamm** [comment]
bors retry

**Comment by johnrwatson** [comment]
bors retry

**Pull request merged**
