### PR TITLE
chore(cleanup): Remove council...

### PR DESCRIPTION
**Pull request by stack72**
Pouring one out for council! Fare thee well!!

### CODE REVIEW

**Comment by stack72** [comment]
bors try

**Comment by stack72** [comment]
bors try

**Review by nickgerace — APPROVED** [review]

**Comment by nickgerace** [comment]
Approved given the overall idea. I think there are likely a few missing places still that we could regex search "council" for, but this is the right direction!

**Comment by stack72** [comment]
bors try

**Comment by stack72** [comment]
bors merge

**Pull request merged**
