### PR TITLE
Redesign validations

### PR DESCRIPTION
**Pull request by paulocsanz**
Initial implementation of the new design

image

image

### CODE REVIEW

**Comment by adamhjk** [comment]
@paulocsanz can we get a couple points of padding between the error box and the field?

**Comment by paulocsanz** [comment]
Sure

**Comment by paulocsanz** [comment]
@adamhjk done 
image

**Comment by adamhjk** [comment]
👍🏼

**Comment by paulocsanz** [comment]
bors merge

**Comment by paulocsanz** [comment]
bors merge

**Comment by paulocsanz** [comment]
bors merge

**Pull request merged**
