### PR TITLE
feat(sdf-server,dal,web): Download workspace snapshots in Admin panel

### PR DESCRIPTION
**Pull request by zacharyhamm**
Adds a workspace and changeset picker, with the ability to download a snapshot to disk directly from SDF.

### CODE REVIEW

**Comment by frantzmiccoli** [comment]
Is this supposed to be anywhere in the version deployed on https://app.systeminit.com/ because I can't find any way to download an export.

**Comment by stack72** [comment]
> Is this supposed to be anywhere in the version deployed on https://app.systeminit.com/ because I can't find any way to download an export.

Hi @frantzmiccoli 

This is not functionality we expose to the user - this is for troubleshootin

**Comment by frantzmiccoli** [comment]
@stack72 thanks for the heads up. So once on a system, there is a vendor lock-in, correct?

**Comment by stack72** [comment]
> @stack72 thanks for the heads up. So once on a system, there is a vendor lock-in, correct?

No, there is a way for users to export their own workspace. System Initiative doesn't have any layers of abstraction for assets soot resources - we are 1:1 with the cloud APIs themselves so you can easily stop using it and still manage your cloud resources

**Pull request merged**
