### PR TITLE
feat(dal,sdf,web): Make components not grow across parent borders on type change

### PR DESCRIPTION
**Pull request by vbustamante**
Also fixes:
- moving children alongside group
- detaching/reparenting multiple components in a single call

### CODE REVIEW

**Review by jobelenus — APPROVED** [review]
:shipit: looks great, thanks for working on this and cleaning up my mess from batching this up...

**Comment by vbustamante** [comment]
bors merge

**Comment by vbustamante** [comment]
bors merge

**Comment by fnichol** [comment]
bors retry

**Pull request merged**
