### PR TITLE
chore: upgrade rust to version 1.82

### PR DESCRIPTION
**Pull request by sprutton1**
The magic `nix flake lock --update-input rust-overlay`

### CODE REVIEW

**Review by fnichol — DISMISSED** [review]
Zoom peer reviewed!

**Review by fnichol — APPROVED** [review]
Ok, too many pints to address, thank goodness!

**Comment by zacharyhamm** [comment]
Did you run `cargo clippy --tests` ?

**Comment by zacharyhamm** [comment]
Oh and it also looks like you'll have to update the macro tests, which depend on exact compiler output

**Comment by zacharyhamm** [comment]
I believe you can run this: `cd lib/dal-macros; TRYBUILD=overwrite cargo test`

**Comment by zacharyhamm** [comment]
then commit the updated stderr files

**Comment by sprutton1** [comment]
> I believe you can run this: `cd lib/dal-macros; TRYBUILD=overwrite cargo test`

This works, too. `TRYBUILD=overwrite buck2 run lib/dal-macros:test-unit`

> Did you run `cargo clippy --tests` ?

Yep, all good.

**Review by zacharyhamm — APPROVED** [review]

**Pull request merged**
