### PR TITLE
feat: add ssl to postgres

### PR DESCRIPTION
**Pull request by sprutton1**
Shhhhhhhhh, this PR didn't happen today. I definitely posted this yesterday. 

Anyways, this adds SSL to postgres connections. I also added a root cert to the docker image so we can use SSL locally and in the launcher. I'm really not sure how to test this for the module-index and I have a feeling all of the tests are going to fail unless we stage this in multiple parts. Merging this should wait until next year.

P.S. I need to do some more work ensuring the launcher still works.

### CODE REVIEW

**Comment by paulocsanz** [comment]
bors try

**Comment by sprutton1** [comment]
bors try

**Comment by sprutton1** [comment]
bors try

**Comment by sprutton1** [comment]
bors try

**Pull request merged**
