### PR TITLE
chore(dal): Ensure that all different get_code Language types are covered

### PR DESCRIPTION
**Pull request by stack72**
This introduces a new test schema - Katy Perry - it's all codegen funcs and no actions :D

### CODE REVIEW

**Comment by stack72** [comment]
bors merge

**Review by nickgerace — APPROVED** [review]
Approved in last PR (https://github.com/systeminit/si/pull/3430), so approved here

**Comment by stack72** [comment]
bors try

**Comment by stack72** [comment]
bors cancel

**Comment by stack72** [comment]
bors merge

**Pull request merged**
