### PR TITLE
feat(si): Recreate SDF or Web containers when port mappings change

### PR DESCRIPTION
**Pull request by stack72**
Closes: #2700

If you want to  change the port map for SDF or Web, then you'd currently
need to stop and delete the containers manually then re-run start

With this PR we can now do the following:

```
si --sdf-port 5157 start
```

This caused the Launcher to act as follows:

```
Container Port Mappings have changed for local-web-1 so recreating
Stopping container /local-web-1
Deleting container: local-web-1 (4d15095f701d8f2872a4e5a838f1187d1e0b980297bd23d15c21bc966eb41188)
Starting systeminit/web:stable as local-web-1
All system components running... System Initiative is alive!

You can now use the `si launch` command to open the System Initiative web portal:
```

### CODE REVIEW

**Comment by keeb** [comment]
Need to check what happens when it's stopped (not `running`) but `created`. I don't think this is captured, but happens as a result of rebooting the machine in my case.

In the case where it's running and needs to be updated - we're 👍

**Comment by stack72** [comment]
bors merge

**Comment by stack72** [comment]
bors cancel

**Comment by stack72** [comment]
@keeb I found the fix to the usecase where the machine wasn't started - works in that case now too

**Review by paulocsanz — APPROVED** [review]

**Comment by stack72** [comment]
bors merge

**Pull request merged**
