### PR TITLE
codemirror cursor colors

### PR DESCRIPTION
**Pull request by theoephraim**
copying the yjs codemirror plugin into our monorepo for now as activity is low and we will very likely be making more modifications. Eventually we can break it back out and publish, but this should make things easy for now...

also note that we are being dumb here about  leaving their existing build process intact and will just manually call `pnpm dist` and check in the dist folder. We'll very likely convert to proper typescript and fix this setup.

### CODE REVIEW

**Review by paulocsanz — APPROVED** [review]
Thank you for this!

**Comment by paulocsanz** [comment]
bors merge

**Comment by theoephraim** [comment]
bors retry

**Comment by theoephraim** [comment]
bors merge

**Comment by paulocsanz** [comment]
bors merge

**Pull request merged**
