### PR TITLE
Make it obvious how attribute panel gets its data

### PR DESCRIPTION
**Pull request by stack72**

### CODE REVIEW

**Comment by stack72** [comment]
bors try

**Comment by paulocsanz** [comment]
bors merge

**Comment by paulocsanz** [comment]
bors merge

**Review by paulocsanz — APPROVED** [review]

**Comment by stack72** [comment]
bors try

**Comment by vbustamante** [comment]
bors merge

**Comment by vbustamante** [comment]
bors merge

**Comment by vbustamante** [comment]
bors merge

**Comment by vbustamante** [comment]
bors merge

**Comment by vbustamante** [comment]
bors merge

**Comment by vbustamante** [comment]
bors merge

**Comment by vbustamante** [comment]
bors merge

**Comment by vbustamante** [comment]
bors try

**Comment by vbustamante** [comment]
bors merge

**Comment by vbustamante** [comment]
bors merge

**Comment by vbustamante** [comment]
bors merge

**Comment by vbustamante** [comment]
bors try

**Comment by vbustamante** [comment]
bors merge

**Comment by vbustamante** [comment]
bors merge

**Comment by vbustamante** [comment]
bors merge

**Comment by vbustamante** [comment]
bors merge

**Comment by vbustamante** [comment]
bors merge

**Pull request merged**
