### PR TITLE
chore(docs): update description of `flake.nix`

### PR DESCRIPTION
**Pull request by fnichol**
This will trigger everything to rebuild, yay!

### CODE REVIEW

**Review by johnrwatson — APPROVED** [review]
LGTM!

**Review by nickgerace — APPROVED** [review]

**Review by sprutton1 — APPROVED** [review]

**Comment by fnichol** [comment]
bors merge

**Comment by fnichol** [comment]
bors retry

**Comment by fnichol** [comment]
bors merge

**Pull request merged**
