### PR TITLE
BUG-142 debounce & batch prop edits at 1 second

### PR DESCRIPTION
**Pull request by jobelenus**
We probably don't need this if we can avoid using materialized view which generates conflicts and Adam's "send WsEvent after rebaser commits" is completed.

### CODE REVIEW

**Review by nickgerace — APPROVED** [review]

**Comment by jobelenus** [comment]
bors try

**Comment by jobelenus** [comment]
bors try

**Comment by jobelenus** [comment]
bors try

**Comment by jobelenus** [comment]
bors try

**Pull request closed without merging**
