### PR TITLE
chore(*): layer-db tracks function execution

### PR DESCRIPTION
**Pull request by nickgerace**
This PR makes layer-db track function execution in func_runs() and
func_run_logs() tables. It also removes the following concepts:

* Func Bindings
* Func Binding Return Values
* Func Executions
* Actions v1

We have not cleaned up the old standard model tables, but other than
that, we're gtg.

### CODE REVIEW

**Comment by fnichol** [comment]
bors try

**Comment by stack72** [comment]
The main issue I see here is that a failed action will still set a resource prop - it's empty but it's still set nonetheless and therefore the component can never be deleted

**Comment by johnrwatson** [comment]
bors cancel

**Comment by adamhjk** [comment]
bors try

**Comment by adamhjk** [comment]
bors merge

**Pull request merged**
